### PR TITLE
Adding libsuitesparseconfig to debian install

### PR DESCRIPTION
**Pull request by AnHeuermann**
I also ordered the libs a tiny bit.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@sjoelund This should fix https://trac.openmodelica.org/OpenModelica/ticket/6375. Can you review and merge if its looking correct?

**Comment by sjoelund** [comment]
Ah, I thought suitesparse was used by OMC, too. So I had it as part of libomc. If you add the config to here, you need to remove it from the other file

**Comment by AnHeuermann** [comment]
Ah I didn't even see you had fixed it already until just now.

SuiteSparse should only be used from the C and C++ runtime, but both link to the libs in `lib/**/omc/`. So I think adding them to https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/master/debian/libomcsimulation.install should be better, at least the other SuiteSparse libs are there as well.

**Comment by AnHeuermann** [comment]
Is the order important? I just sorted them alphabetically.
And how are the *.install files are used?

**Comment by sjoelund** [comment]
Order doesn't matter. The files listed become part of the corresponding .deb package. You can't have the same file in two installed packages.

**Comment by AnHeuermann** [comment]
I think we should merge this PR so the master and maintenance/v1.17 branches are in sync.

**Pull request merged**
